// Code generated by gorm.io/gen. DO NOT EDIT.
package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UUID                 string    	`gorm:"column:uuid;primaryKey" json:"uuid"`
	CreatedAt            time.Time 	`gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt            time.Time 	`gorm:"column:updated_at;not null" json:"updated_at"`
	Email                string    	`gorm:"column:email;not null" json:"email"`
	Name                 string    	`gorm:"column:name;not null" json:"name"`
	PasswordHash         []uint8   	`gorm:"column:password_hash;not null" json:"password_hash"`
	Salt                 []uint8   	`gorm:"column:salt;not null" json:"salt"`
	PasswordIterations   int32    	`gorm:"column:password_iterations;not null" json:"password_iterations"`
	PasswordHint         *string    `gorm:"column:password_hint" json:"password_hint"`
	Akey                 string    	`gorm:"column:akey;not null" json:"akey"`
	PrivateKey           string    	`gorm:"column:private_key" json:"private_key"`
	PublicKey            string    	`gorm:"column:public_key" json:"public_key"`
	TotpSecret           *string    `gorm:"column:totp_secret" json:"totp_secret"`
	TotpRecover          *string    `gorm:"column:totp_recover" json:"totp_recover"`
	SecurityStamp        string    	`gorm:"column:security_stamp;not null" json:"security_stamp"`
	EquivalentDomains    string    	`gorm:"column:equivalent_domains;not null" json:"equivalent_domains"`
	ExcludedGlobals      string    	`gorm:"column:excluded_globals;not null" json:"excluded_globals"`
	ClientKdfType        int32     	`gorm:"column:client_kdf_type;not null" json:"client_kdf_type"`
	ClientKdfIter        int32     	`gorm:"column:client_kdf_iter;not null;default:100000" json:"client_kdf_iter"`
	VerifiedAt           *time.Time `gorm:"column:verified_at" json:"verified_at"`
	LastVerifyingAt      *time.Time `gorm:"column:last_verifying_at" json:"last_verifying_at"`
	LoginVerifyCount     int32     	`gorm:"column:login_verify_count;not null" json:"login_verify_count"`
	EmailNew             *string    `gorm:"column:email_new;default:NULL" json:"email_new"`
	EmailNewToken        *string    `gorm:"column:email_new_token;default:NULL" json:"email_new_token"`
	Enabled              bool      	`gorm:"column:enabled;not null;default:true" json:"enabled"`
	StampException       *string    `gorm:"column:stamp_exception" json:"stamp_exception"`
	APIKey               *string    `gorm:"column:api_key" json:"api_key"`
	AvatarColor          *string    `gorm:"column:avatar_color" json:"avatar_color"`
	ClientKdfMemory      *int32     `gorm:"column:client_kdf_memory" json:"client_kdf_memory"`
	ClientKdfParallelism *int32     `gorm:"column:client_kdf_parallelism" json:"client_kdf_parallelism"`
	ExternalID           *string    `gorm:"column:external_id" json:"external_id"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
