// Code generated by gorm.io/gen. DO NOT EDIT.
package model

const TableNameUsersOrganization = "users_organizations"

// UsersOrganization mapped from table <users_organizations>
type UsersOrganization struct {
	UUID             string 	`gorm:"column:uuid;primaryKey" json:"uuid"`
	UserUUID         string 	`gorm:"column:user_uuid;not null" json:"user_uuid"`
	OrgUUID          string 	`gorm:"column:org_uuid;not null" json:"org_uuid"`
	AccessAll        bool   	`gorm:"column:access_all;not null" json:"access_all"`
	Akey             string 	`gorm:"column:akey;not null" json:"akey"`
	Status           int32  	`gorm:"column:status;not null" json:"status"`
	Atype            int32  	`gorm:"column:atype;not null" json:"atype"`
	ResetPasswordKey *string 	`gorm:"column:reset_password_key" json:"reset_password_key"`
	ExternalID       *string 	`gorm:"column:external_id" json:"external_id"`
}

// TableName UsersOrganization's table name
func (*UsersOrganization) TableName() string {
	return TableNameUsersOrganization
}
